import { Build, ComponentCategory } from "@shared"
import { useState } from "react"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@components/ui/dialog"
import { Button } from "@components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@components/ui/tabs"
import { Download, FileText, Image } from "lucide-react"

interface BuildExportProps {
  build: Build
  components: Partial<Record<ComponentCategory, any>>
  trigger?: React.ReactNode
}

const CATEGORY_LABELS: Record<ComponentCategory, string> = {
  [ComponentCategory.CPU]: "CPU",
  [ComponentCategory.CPU_COOLER]: "CPU Cooler",
  [ComponentCategory.MOTHERBOARD]: "Motherboard",
  [ComponentCategory.MEMORY]: "Memory",
  [ComponentCategory.STORAGE]: "Storage",
  [ComponentCategory.VIDEO_CARD]: "Video Card",
  [ComponentCategory.CASE]: "Case",
  [ComponentCategory.POWER_SUPPLY]: "Power Supply",
  [ComponentCategory.MONITOR]: "Monitor",
  [ComponentCategory.OS]: "OS",
  [ComponentCategory.CASE_FAN]: "Case Fan",
  [ComponentCategory.THERMAL_PASTE]: "Thermal Paste",
}

export function BuildExport({ build, components, trigger }: BuildExportProps) {
  const [copied, setCopied] = useState(false)

  const generateMarkdown = (): string => {
    let markdown = `# ${build.name}\n\n`

    if (build.description) {
      markdown += `${build.description}\n\n`
    }

    if (build.useCase) {
      markdown += `**Use Case:** ${build.useCase}\n\n`
    }

    markdown += `## Components\n\n`

    let total = 0
    Object.entries(components).forEach(([category, component]) => {
      if (component) {
        const label = CATEGORY_LABELS[category as ComponentCategory]
        const price = component.prices?.[0]?.price || 0
        total += price

        markdown += `**${label}**: ${component.name}`
        if (price > 0) {
          markdown += ` - $${price.toFixed(2)}`
        }
        markdown += `\n`
      }
    })

    markdown += `\n**Total**: $${total.toFixed(2)}\n`

    if (build.totalWattage) {
      markdown += `\n**Estimated Wattage**: ${build.totalWattage}W\n`
    }

    markdown += `\n---\n`
    markdown += `\nGenerated by [PCBuilderAI](https://pcpartfinder-app.vercel.app)\n`
    markdown += `Share URL: ${window.location.origin}/builds/${build.shareId}\n`

    return markdown
  }

  const handleCopyMarkdown = async () => {
    const markdown = generateMarkdown()
    await navigator.clipboard.writeText(markdown)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownloadMarkdown = () => {
    const markdown = generateMarkdown()
    const blob = new Blob([markdown], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${build.name.replace(/\s+/g, "-")}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handleDownloadImage = () => {
    // For now, we'll use print dialog
    // In a real implementation, you'd use html2canvas or similar
    window.print()
  }

  return (
    <Dialog>
      <DialogTrigger asChild>
        {trigger || (
          <Button variant="outline">
            <Download className="h-4 w-4 mr-2" />
            Export
          </Button>
        )}
      </DialogTrigger>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Export Build</DialogTitle>
          <DialogDescription>
            Export your build as markdown or image
          </DialogDescription>
        </DialogHeader>

        <Tabs defaultValue="markdown">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="markdown">
              <FileText className="h-4 w-4 mr-2" />
              Markdown
            </TabsTrigger>
            <TabsTrigger value="image">
              <Image className="h-4 w-4 mr-2" />
              Image
            </TabsTrigger>
          </TabsList>

          <TabsContent value="markdown" className="space-y-4">
            <div className="space-y-2">
              <p className="text-sm text-muted-foreground">
                Copy the markdown to clipboard or download as a file
              </p>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  className="flex-1"
                  onClick={handleCopyMarkdown}
                >
                  {copied ? "Copied!" : "Copy to Clipboard"}
                </Button>
                <Button
                  variant="default"
                  className="flex-1"
                  onClick={handleDownloadMarkdown}
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download .md
                </Button>
              </div>
            </div>

            {/* Preview */}
            <div className="border rounded-lg p-4 bg-muted/30 max-h-64 overflow-y-auto">
              <pre className="text-xs whitespace-pre-wrap">{generateMarkdown()}</pre>
            </div>
          </TabsContent>

          <TabsContent value="image" className="space-y-4">
            <div className="space-y-2">
              <p className="text-sm text-muted-foreground">
                Export your build as an image for sharing on social media
              </p>
              <Button
                variant="default"
                className="w-full"
                onClick={handleDownloadImage}
              >
                <Download className="h-4 w-4 mr-2" />
                Print / Save as PDF
              </Button>
              <p className="text-xs text-muted-foreground">
                This will open the print dialog where you can save as PDF or
                print to a file.
              </p>
            </div>
          </TabsContent>
        </Tabs>
      </DialogContent>
    </Dialog>
  )
}
